Appointment service unavailability coflict
bahmni-msf/openmrs-module-appointments pull request #9
Opened 2019-09-25 12:35 UTC by AlekhyaYalla

2019-09-25 14:35 UTC, sowmika148 commented on api/src/main/java/org/openmrs/module/appointments/model/AppointmentConflict.java
> +public class AppointmentConflict {
Can this be Map<Type, List<Appointment>> ?

2019-09-26 05:38 UTC, sowmika148 commented on omod/src/main/java/org/openmrs/module/appointments/web/controller/RecurringAppointmentsController.java
> +                throw new APIException(errors.getAllErrors().get(0).getCodes()[1]);
We are using error code as error message. Ideally we should not be doing that. We should use peoper code and message. See if you can refactor that in all places.

2019-09-26 05:38 UTC, sowmika148 commented on omod/src/main/java/org/openmrs/module/appointments/web/controller/RecurringAppointmentsController.java
> +            List<Appointment> appointments = recurringAppointmentsService.generateRecurringAppointments(recurringAppointmentRequest);
Not sure if generateAppointments has to be called when it is edit

2019-09-26 06:09 UTC, shivarach requested changes

2019-09-26 06:09 UTC, shivarach commented on omod/src/main/java/org/openmrs/module/appointments/web/controller/RecurringAppointmentsController.java
> +            return new ResponseEntity<>(RestUtil.wrapErrorResponse(e, e.getMessage()), HttpStatus.BAD_REQUEST);
We say bad request only when the request doesn't have expected data or incorrect format, in this case, you may want to use INTERNAL SERVER ERROR

2019-09-26 06:09 UTC, shivarach commented on api/src/main/java/org/openmrs/module/appointments/conflicts/impl/AppointmentServiceUnavailabilityConflict.java
> +    private long getEpochTime(long date) {
epoch means :)

2019-09-26 06:09 UTC, shivarach commented on api/src/main/java/org/openmrs/module/appointments/conflicts/impl/AppointmentServiceUnavailabilityConflict.java
> +    private AppointmentConflict checkConflicts(Appointment appointment, AppointmentServiceDefinition appointmentServiceDefinition) {
This method is hard to understand, see if you can increase readability

2019-09-26 06:09 UTC, shivarach commented on api/src/main/java/org/openmrs/module/appointments/conflicts/impl/AppointmentServiceUnavailabilityConflict.java
> +        return null;
Ternary operatory looks good

2019-09-26 06:09 UTC, shivarach commented on api/src/main/resources/moduleApplicationContext.xml
> +                        <bean class="org.openmrs.module.appointments.conflicts.impl.AppointmentServiceUnavailabilityConflict"/>
The intention looks like expecting a list, probably you need to give interface in bean class?

2019-09-26 06:09 UTC, shivarach commented on api/src/test/resources/TestingApplicationContext.xml
> +                        <bean class="org.openmrs.module.appointments.conflicts.impl.AppointmentServiceUnavailabilityConflict"/>
Same as above

2019-09-26 06:09 UTC, shivarach commented on omod/src/main/java/org/openmrs/module/appointments/web/mapper/RecurringAppointmentMapper.java
> +                Collectors.mapping(a -> appointmentMapper.constructResponse(a.getAppointment()), Collectors.toList())));
use proper naming instead of **a**

2019-09-26 06:09 UTC, shivarach commented on omod/src/main/java/org/openmrs/module/appointments/web/controller/AppointmentController.java
> +            return new ResponseEntity<>(RestUtil.wrapErrorResponse(e, e.getMessage()), HttpStatus.BAD_REQUEST);
Should be INTERNAL SERVER ERROR?

2019-09-26 06:09 UTC, shivarach commented on api/src/main/resources/moduleApplicationContext.xml
> +                        <bean class="org.openmrs.module.appointments.conflicts.impl.AppointmentServiceUnavailabilityConflict"/>
class should be interface?

2019-09-26 08:29 UTC, AlekhyaYalla commented on api/src/main/java/org/openmrs/module/appointments/conflicts/impl/AppointmentServiceUnavailabilityConflict.java
> +    private long getEpochTime(long date) {
'epoch' is often used as a synonym for Unix time

2019-09-26 08:31 UTC, AlekhyaYalla commented on api/src/main/java/org/openmrs/module/appointments/conflicts/impl/AppointmentServiceUnavailabilityConflict.java
> +    private AppointmentConflict checkConflicts(Appointment appointment, AppointmentServiceDefinition appointmentServiceDefinition) {
Modified. please have a look into it

2019-09-26 08:34 UTC, AlekhyaYalla commented on omod/src/main/java/org/openmrs/module/appointments/web/controller/RecurringAppointmentsController.java
> +            return new ResponseEntity<>(RestUtil.wrapErrorResponse(e, e.getMessage()), HttpStatus.BAD_REQUEST);
Yes, modifying it to internal_server_error.

2019-09-26 08:37 UTC, AlekhyaYalla commented on api/src/main/java/org/openmrs/module/appointments/conflicts/impl/AppointmentServiceUnavailabilityConflict.java
> +        return null;
Agreed Modified.

2019-09-26 18:38 UTC, sowmika148 commented on api/src/main/java/org/openmrs/module/appointments/helper/AppointmentServiceHelper.java
> +                .filter(appointment -> !(appointment.getVoided() || appointment.getStartDateTime().before(new Date())))
Can we use isFutureAppointment in appointment.java? Also when we are comparing the date we need to compare with start of day not with time

2019-09-26 18:38 UTC, sowmika148 commented on api/src/main/java/org/openmrs/module/appointments/helper/AppointmentServiceHelper.java
> +                .filter(appointment -> !(appointment.getVoided() || appointment.getStartDateTime().before(new Date())))
While checking conflicts so we include all statuses - MISSED, SCHEDULED, CANCELLED all of them?

2019-09-26 18:48 UTC, sowmika148 commented on omod/src/main/java/org/openmrs/module/appointments/web/controller/AppointmentController.java
> +    public ResponseEntity<Object> conflicts(@RequestBody AppointmentRequest appointmentRequest) {
Can we move this to AppointmentsController

2019-10-01 07:08 UTC, closed without merging